/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get API health
         * @description Public health check. It does not require a Bearer token.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a Bearer token
         * @description Public login endpoint. Use the returned access token as `Authorization: Bearer <access_token>` for protected operations.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/change-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Change the admin password and rotate Bearer tokens
         * @description Requires a valid Bearer token. On success, all previous tokens are invalidated and a replacement token is returned.
         */
        post: operations["changePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get current product runtime state
         * @description Answers what the GP product core is doing now: current discovery run, core jobs and product runtime state.
         */
        get: operations["getCoreStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/strategy-discovery/start-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start a strategy discovery run
         * @description Routes a discovery request by mode. The request contains final concrete domains and settings, not a preset id or live preset link.
         */
        post: operations["startStrategyDiscoveryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/strategy-discovery/stop-current-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop the current strategy discovery run */
        post: operations["stopCurrentStrategyDiscoveryRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/strategy-discovery/current-run-progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current run progress */
        get: operations["getCurrentStrategyDiscoveryProgress"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/strategy-discovery/current-run-latest-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest log tail for the current run */
        get: operations["getCurrentStrategyDiscoveryLatestLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/strategy-discovery/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Check discovery prerequisites
         * @description Checks GP/zapret/v2fly prerequisites needed to start discovery. It reports product readiness, not OS monitoring metrics.
         */
        get: operations["getStrategyDiscoveryPreflight"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/presets/domain-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List stored domain lists
         * @description Returns only real stored lists: required first, desired second, then user lists in storage order.
         */
        get: operations["getDomainLists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/presets/save-domain-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save one domain list
         * @description Saves one required, desired or user domain list. The list contents replace the previous contents of that list.
         */
        post: operations["saveDomainList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/presets/delete-user-domain-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete selected user domain lists
         * @description Deletes only explicitly listed user-created domain lists. The list_ids array must not be empty; to delete all user lists, the caller must enumerate every user list id. Required and desired lists cannot be deleted by this method.
         */
        post: operations["deleteUserDomainLists"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/presets/v2fly/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List local v2fly categories
         * @description Returns local v2fly categories and storage state. If storage is not prepared, the response is still 200 with storage.state=missing.
         */
        get: operations["getV2flyCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/presets/v2fly/category-domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get domains from one v2fly category */
        get: operations["getV2flyCategoryDomains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/backups/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a GP data backup */
        post: operations["createBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/backups/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List local backups */
        get: operations["listBackups"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/backups/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore a GP data backup
         * @description Restores the selected snapshot synchronously after UI/client confirmation. There is no separate restore-preview endpoint in the target contract; the response is sent only after the restore succeeds.
         */
        post: operations["restoreBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/backups/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete a backup snapshot */
        post: operations["deleteBackup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/backups/download-archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download a backup archive */
        get: operations["downloadBackupArchive"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/backups/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a backup archive
         * @description Accepts a ZIP backup, validates structure, checksum and compatibility, then imports it into backup storage.
         */
        post: operations["uploadBackupFile"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/clean-install-vaults/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the one pending device-local clean-install vault
         * @description Creates one pending device-local vault. Its local handoff remains on this device; the response contains public metadata only.
         */
        post: operations["createCleanInstallVault"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/clean-install-vaults/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List pending clean-install vault metadata */
        get: operations["listCleanInstallVaults"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/clean-install-vaults/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get public status of one pending clean-install vault */
        get: operations["getCleanInstallVaultStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/clean-install-vaults/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restore and delete a verified pending clean-install vault
         * @description Requires explicit confirmation. The operation completes only after semantic verification, SQLite readiness/integrity verification and deletion of the source vault. Failed paths retain vault and handoff.
         */
        post: operations["restoreCleanInstallVault"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/run-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get discovery run settings */
        get: operations["getRunSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/run-settings/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save discovery run settings */
        post: operations["saveRunSettings"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/runs/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full run history
         * @description Returns product run history without UI pagination. UI slices belong to /api/web/...
         */
        get: operations["getRunHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/runs/latest-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest log tail for a run */
        get: operations["getRunLatestLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/strategy-candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get filtered strategy candidates
         * @description Returns normalized product candidate data only for filtered requests. At least one filter is required. Use /api/core/strategy-candidates/export for full streaming export.
         */
        get: operations["getStrategyCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/strategy-candidates/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream strategy candidates as NDJSON
         * @description Streams one StrategyCandidate JSON object per line. This endpoint can be called without filters for a full export; optional filters use the same semantics as /api/core/strategy-candidates. It is intended for large exports and external clients.
         */
        get: operations["exportStrategyCandidates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/core/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get normalized product events */
        get: operations["getCoreEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get installed GP service status
         * @description Answers whether the installed GP service and its data/install state are alive.
         */
        get: operations["getServiceStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service/releases/available": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get available GP releases */
        get: operations["getAvailableReleases"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service/v2fly/local-storage-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get local v2fly storage status */
        get: operations["getV2flyLocalStorageStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service/v2fly/check-updates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check v2fly source updates */
        post: operations["checkV2flyUpdates"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/service/v2fly/update-local-storage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update local v2fly storage */
        post: operations["updateV2flyLocalStorage"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Web UI system status
         * @description Returns Web-owned system diagnostics, including zapret2 readiness for the System card. Core status remains limited to product runtime state.
         */
        get: operations["getWebStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/run-preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Web UI run form preferences
         * @description Returns only штатный Web UI form state. Core start-run receives explicit domains and run parameters, not this saved UI state.
         */
        get: operations["getWebRunPreferences"];
        put?: never;
        /**
         * Save Web UI run form preferences
         * @description Stores штатный Web UI form state for the next browser session. This does not start discovery and does not change durable Core results.
         */
        post: operations["saveWebRunPreferences"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/runs/history-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated run history page for штатный Web UI */
        get: operations["getWebRunHistoryPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/candidate-domain-index-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated candidate domain index page for the Web UI */
        get: operations["getWebCandidateDomainIndexPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/strategy-candidates-page": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated strategy candidates page for штатный Web UI */
        get: operations["getWebStrategyCandidatesPage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Web UI preset metadata and lists
         * @description Returns штатный Web UI preset metadata plus built-in domain set labels. Domains for custom presets are included only when requested.
         */
        get: operations["getWebPresets"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/presets/domains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a paginated Web UI preset domain page */
        get: operations["getWebPresetDomains"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/presets/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save a Web UI preset domain list */
        post: operations["saveWebPreset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/presets/delete-user-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Delete Web UI user preset lists */
        post: operations["deleteWebUserPresetLists"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a штатный Web UI event slice */
        get: operations["getWebEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/web/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream штатный Web UI events
         * @description Server-sent event stream for live Web UI refreshes. Event names match the Web UI event types returned by /api/web/events.
         */
        get: operations["streamWebEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @constant */
            status: "ok";
        };
        LoginRequest: {
            /** @example admin */
            username: string;
            /** Format: password */
            password: string;
        };
        ChangePasswordRequest: {
            /** Format: password */
            current_password: string;
            /** Format: password */
            new_password: string | "admin" | unknown;
        };
        BearerToken: {
            access_token: string;
            /** @constant */
            token_type: "Bearer";
            /** @constant */
            expires_in: 86400;
        };
        BackupRestoreAccepted: {
            /** @constant */
            accepted: true;
            /** @constant */
            status: "success";
            snapshot_id: string;
        };
        AvailableReleases: {
            current: components["schemas"]["InstalledVersion"];
            releases: components["schemas"]["ReleaseInfo"][];
            stable_release_url?: string;
            prerelease_url?: string;
        };
        BackupActionRequest: {
            snapshot_id: string;
        };
        BackupSnapshot: {
            snapshot_id: string;
            /** Format: date-time */
            created_at: string;
            schema_version: string;
            filename?: string;
            size_bytes?: number;
            checksum?: string;
            entity_counts?: components["schemas"]["EntityCounts"];
        };
        BackupsResponse: {
            backups: components["schemas"]["BackupSnapshot"][];
        };
        CleanInstallVaultCreateResponse: {
            vault_id: string;
            archive_sha256: string;
            archive_size_bytes: number;
            /** @constant */
            schema_version: "7";
            semantic_manifest: {
                [key: string]: unknown;
            };
        };
        CleanInstallVaultStatus: {
            vault_id: string;
            created_at: string;
            /** @constant */
            schema_version: "7";
            archive_sha256: string;
            archive_size_bytes: number;
            verification: string;
            /** @constant */
            pending: true;
        };
        CleanInstallVaultListResponse: {
            vaults: components["schemas"]["CleanInstallVaultStatus"][];
        };
        CleanInstallVaultRestoreRequest: {
            vault_id: string;
            /** @constant */
            confirm_restore: true;
        };
        CleanInstallVaultRestoreResponse: {
            /** @constant */
            completed: true;
            vault_id: string;
            verification: {
                [key: string]: unknown;
            };
            storage_status: {
                [key: string]: unknown;
            };
            cleanup: {
                [key: string]: unknown;
            };
        };
        CoreStatus: {
            /** @enum {string} */
            state: "idle" | "running" | "stopping" | "degraded" | "error";
            current_run?: components["schemas"]["RunRef"];
            last_snapshot?: components["schemas"]["PostRunSnapshotOutcome"];
            storage?: components["schemas"]["StorageStatus"];
            /** Format: date-time */
            updated_at?: string;
        };
        WebStatusResponse: {
            version: string;
            state: {
                [key: string]: unknown;
            };
            settings: {
                [key: string]: unknown;
            };
            run_preferences: {
                [key: string]: unknown;
            };
            candidate_version: {
                [key: string]: unknown;
            };
            paths: {
                [key: string]: unknown;
            };
            zapret2: {
                [key: string]: unknown;
            };
        };
        PostRunSnapshotOutcome: {
            /** @constant */
            kind: "snapshot";
            /** @constant */
            status: "success";
            /** Format: date-time */
            completed_at: string;
            snapshot_id: string;
            snapshot?: {
                [key: string]: unknown;
            };
        } | {
            /** @constant */
            kind: "snapshot";
            /** @constant */
            status: "failed";
            /** Format: date-time */
            completed_at: string;
            error_code: string;
            error_message: string;
        };
        DeleteDomainListRequest: {
            list_ids: string[];
        };
        DeleteResult: {
            deleted: number;
        };
        DomainList: {
            list_id: string;
            /** @enum {string} */
            kind: "required" | "desired" | "user";
            name: string;
            domains: string[];
            /** Format: date-time */
            updated_at?: string;
        };
        DomainListsResponse: {
            lists: components["schemas"]["DomainList"][];
        };
        EntityCounts: {
            domains?: number;
            strategies?: number;
            strategy_domain_links?: number;
            domain_lists?: number;
            settings?: number;
        };
        ErrorResponse: {
            error: {
                /** @example invalid_request */
                code: string;
                /** @example The request is invalid. */
                message: string;
                details: {
                    [key: string]: unknown;
                };
            };
        };
        Event: {
            event_id: string;
            type: string;
            /** Format: date-time */
            created_at: string;
            run_id?: string;
            payload?: {
                [key: string]: unknown;
            };
        };
        EventsResponse: {
            events: components["schemas"]["Event"][];
            next_after_id?: string;
        };
        InstalledVersion: {
            version?: string;
            installed_ref?: string;
            commit?: string;
        };
        CandidateDomainIndexItem: {
            domain: string;
            strategy_count: number;
            protocols: components["schemas"]["CandidateDomainProtocolCount"][];
        };
        CandidateDomainProtocolCount: {
            protocol: string;
            count: number;
        };
        CandidateDomainIndexResponse: {
            domains: components["schemas"]["CandidateDomainIndexItem"][];
            total: number;
            strategy_total: number;
            tested_domains?: string[];
            version?: {
                [key: string]: number;
            };
        } & {
            [key: string]: unknown;
        };
        PagedRunHistoryResponse: {
            runs: components["schemas"]["RunHistoryItem"][];
            limit: number;
            offset: number;
            total: number;
            has_more: boolean;
        };
        PagedCandidateDomainIndexResponse: {
            domains: components["schemas"]["CandidateDomainIndexItem"][];
            total: number;
            strategy_total: number;
            tested_domains?: string[];
            version?: {
                [key: string]: number;
            };
            limit: number;
            offset: number;
            has_more: boolean;
        };
        PagedStrategyCandidatesResponse: {
            candidates: components["schemas"]["StrategyCandidate"][];
            total: number;
            limit: number;
            offset: number;
            has_more: boolean;
            tested_domains: string[];
            version: {
                [key: string]: number;
            };
        };
        Pagination: {
            limit: number;
            offset: number;
            total: number;
            has_more: boolean;
        };
        PreflightStatus: {
            ready: boolean;
            checks: components["schemas"]["PreflightCheck"][];
        };
        PreflightCheck: {
            name: string;
            /** @enum {string} */
            status: "ok" | "warning" | "error" | "unknown";
            message?: string;
            details?: {
                [key: string]: unknown;
            };
        };
        ReleaseInfo: {
            version: string;
            /** @enum {string} */
            channel: "stable" | "prerelease";
            ref: string;
            url?: string;
            /** Format: date-time */
            published_at?: string;
        };
        RunAccepted: {
            /** @constant */
            accepted: true;
            run_id: string;
            status: string;
        };
        RunHistoryItem: {
            run_id: string;
            /** @description Runtime execution kind that identifies the discovery workflow which produced the run. */
            kind?: string;
            mode?: components["schemas"]["RunMode"];
            status: components["schemas"]["RunStatus"];
            /** Format: date-time */
            started_at: string;
            /**
             * Format: date-time
             * @description Timestamp recorded for this run history entry; for the initial entry it is the run start time.
             */
            timestamp?: string;
            /** Format: date-time */
            completed_at?: string;
            domains?: string[];
            settings?: {
                [key: string]: unknown;
            };
            summary?: {
                [key: string]: unknown;
            };
        };
        RunHistoryResponse: {
            runs: components["schemas"]["RunHistoryItem"][];
        };
        RunLogTail: {
            run_id: string | null;
            kind: string | null;
            status: string | null;
            stdout_tail: string;
            stdout_append: string;
            stderr_tail: string;
            stderr_append: string;
            stderr_diagnostics: {
                [key: string]: string;
            }[];
            stdout_log?: string;
            stderr_log?: string;
            stdout_size: number;
            stderr_size: number;
            progress: {
                [key: string]: unknown;
            };
            metrics: {
                [key: string]: unknown;
            };
            run_settings: {
                [key: string]: unknown;
            };
        };
        /** @enum {string} */
        RunMode: "standard" | "multi_domain" | "common_strategy";
        RunProgress: {
            run_id?: string;
            status: components["schemas"]["RunStatus"];
            stage?: string;
            current_file?: string;
            domains_total?: number;
            domains_processed?: number;
            attempts_total?: number;
            attempts_processed?: number;
            strategies_total?: number;
            strategies_processed?: number;
            elapsed_seconds?: number;
            eta_seconds?: number;
            avg_attempt_seconds?: number;
        };
        RunRef: {
            run_id: string;
            status: components["schemas"]["RunStatus"];
        };
        RunSettings: {
            curl_parallelism_default?: number;
            curl_parallelism_max?: number;
            curl_max_time?: number;
            curl_max_time_quic?: number;
            curl_max_time_doh?: number;
            enable_ipv6?: boolean;
            debug_stdout?: boolean;
        };
        /** @enum {string} */
        RunStatus: "idle" | "queued" | "running" | "saving" | "stopping" | "stopped" | "success" | "failed" | "timeout";
        SaveDomainListRequest: {
            list_id?: string;
            /** @enum {string} */
            kind: "required" | "desired" | "user";
            name: string;
            domains: string[];
        };
        ServiceStatus: {
            /** @enum {string} */
            state: "active" | "inactive" | "degraded" | "error" | "unknown";
            /** @enum {string} */
            mode: "core" | "monolith" | "web_proxy" | "unknown";
            services: {
                core: components["schemas"]["ServiceComponentStatus"];
                web: components["schemas"]["ServiceComponentStatus"];
            };
            version: components["schemas"]["InstalledVersion"];
            data_state: components["schemas"]["ServiceDataState"];
            /** Format: date-time */
            updated_at: string;
        };
        ServiceComponentStatus: {
            name: string;
            /** @enum {string} */
            state: "active" | "embedded" | "disabled" | "unknown";
            role: string;
            required: boolean;
        };
        ServiceDataState: {
            /** @enum {string} */
            state: "ready" | "missing" | "preparing" | "error" | "unknown";
            state_dir: string;
            v2fly: {
                state: string;
                source_commit: string;
                group_count: number;
            };
        };
        StartRunRequest: {
            mode?: components["schemas"]["RunMode"];
            domains: string[];
            protocols?: ("tcp" | "quic")[];
            curl_parallelism?: number;
            timeout_seconds?: number;
            settings?: {
                curl_max_time?: number;
                curl_max_time_quic?: number;
                curl_max_time_doh?: number;
                debug_stdout?: boolean;
                enable_http?: boolean;
                enable_ipv6?: boolean;
                enable_tls12?: boolean;
                enable_tls13?: boolean;
                include_quic?: boolean;
                repeats?: number;
                repeat_parallel?: boolean;
                /** @enum {string} */
                scan_level?: "quick" | "standard" | "force";
                skip_dnscheck?: boolean;
            };
        };
        StorageStatus: {
            ready?: boolean;
            schema_version?: number;
            state_dir?: string;
        };
        StrategyCandidate: {
            id: string;
            protocol: string;
            args: string;
            status: string;
            first_seen_at?: string;
            last_seen_at?: string;
            fragmentation_class?: string;
            fragmentation_safe?: boolean;
            fragmentation_reason?: string;
            family?: string;
            family_key?: string;
            family_rank?: number;
            family_reason?: string;
            seen?: components["schemas"]["StrategyCandidateSeen"][];
            common_seen?: components["schemas"]["StrategyCandidateCommonSeen"][];
        };
        StrategyCandidateSeen: {
            run_id?: string;
            domain: string;
            test?: string;
            ip_version?: string;
            seen_at?: string;
        };
        StrategyCandidateCommonSeen: {
            domains: string[];
        };
        StrategyCandidatesResponse: {
            candidates: components["schemas"]["StrategyCandidate"][];
            total: number;
            filters: components["schemas"]["StrategyCandidateFilters"];
        };
        V2flyCategoriesResponse: {
            categories: components["schemas"]["V2flyCategory"][];
            storage?: components["schemas"]["V2flyStorageStatus"];
        };
        V2flyCategory: {
            name: string;
            domain_count?: number;
        };
        V2flyCategoryDomainsResponse: {
            category: string;
            domains: string[];
            storage?: components["schemas"]["V2flyStorageStatus"];
        };
        V2flyStorageStatus: {
            /** @enum {string} */
            state: "ready" | "missing" | "preparing" | "error" | "unknown";
            source_repo?: string;
            source_ref?: string;
            source_commit?: string;
            /** Format: date-time */
            prepared_at?: string;
            group_count?: number;
            archive_sha256?: string;
            catalog_sha256?: string;
            last_update_check?: {
                [key: string]: unknown;
            };
        };
        WebRunPreferences: {
            domains: string[];
            domain_preset: string;
            /** @enum {string} */
            discovery_profile: "quick" | "standard" | "force" | "custom";
            /** @enum {string} */
            run_mode: "standard" | "multi";
            curl_parallelism?: number;
            enable_http?: boolean;
            enable_tls12?: boolean;
            enable_tls13?: boolean;
            include_quic?: boolean;
            enable_ipv6?: boolean;
            /** @enum {string} */
            scan_level?: "quick" | "standard" | "force";
            repeats?: number;
            repeat_parallel?: boolean;
            skip_dnscheck?: boolean;
            skip_ipblock?: boolean;
            limit_time_enabled?: boolean;
            timeout_hours?: number;
        };
        WebRunPreferencesResponse: {
            run_preferences: components["schemas"]["WebRunPreferences"];
        };
        WebRunPreferencesSaveRequest: {
            run_preferences: components["schemas"]["WebRunPreferences"];
        };
        /** @enum {string} */
        WebPresetScope: "finder" | "common";
        /**
         * @default user
         * @enum {string}
         */
        WebPresetKind: "user" | "system";
        WebPresetMetadata: {
            name: string;
            kind: components["schemas"]["WebPresetKind"];
            label: string;
            enabled_count: number;
            total_count: number;
            updated_at: string;
        };
        WebPresetMetadataScope: {
            [key: string]: components["schemas"]["WebPresetMetadata"];
        };
        WebPresetMetadataMap: {
            finder: components["schemas"]["WebPresetMetadataScope"];
            common: components["schemas"]["WebPresetMetadataScope"];
        };
        WebPresetDomainMapScope: {
            [key: string]: string[];
        };
        WebPresetDomainMap: {
            finder: components["schemas"]["WebPresetDomainMapScope"];
            common: components["schemas"]["WebPresetDomainMapScope"];
        };
        WebBuiltinPresetSource: {
            type: string;
            source: string;
            coverage_note: string;
            key: string;
            url: string;
        };
        WebPresetsResponse: {
            metadata: components["schemas"]["WebPresetMetadataMap"];
            system_metadata: components["schemas"]["WebPresetMetadataMap"];
            system: components["schemas"]["WebPresetDomainMap"];
            custom: components["schemas"]["WebPresetDomainMap"];
            domain_sets: {
                [key: string]: string[];
            };
            builtin: {
                [key: string]: components["schemas"]["WebBuiltinPresetSource"];
            };
        };
        WebPresetSaveRequest: {
            scope: components["schemas"]["WebPresetScope"];
            name: string;
            kind?: components["schemas"]["WebPresetKind"];
            domains: string[];
        };
        WebPresetDeleteUserListsRequest: {
            scope: components["schemas"]["WebPresetScope"];
            names?: string[];
            name?: string;
        } | unknown | unknown;
        WebPresetDomainItem: {
            domain: string;
            position: number;
            enabled: boolean;
        };
        WebPresetDomainsResponse: {
            scope: string;
            name: string;
            kind: string;
            query: string;
            limit: number;
            offset: number;
            total: number;
            has_more: boolean;
            domains: components["schemas"]["WebPresetDomainItem"][];
        };
        StrategyCandidateFilters: {
            domains?: string[];
            strategy_ids?: string[];
            protocols?: string[];
            source_modes?: ("single_domain" | "multi_domain")[];
            families?: string[];
            query?: string;
        };
        ServiceActionResult: {
            status: string;
            operation_id: string;
            storage: components["schemas"]["V2flyStorageStatus"];
            result?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Bearer authentication is required or the supplied token is invalid */
        AuthenticationRequired: {
            headers: {
                /** @description Bearer authentication challenge emitted by the server */
                "WWW-Authenticate"?: "Bearer";
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Runtime is busy */
        RuntimeBusy: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @example 50 */
        Limit: number;
        /** @example 0 */
        Offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API is healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Authenticated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BearerToken"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["AuthenticationRequired"];
            503: components["responses"]["Error"];
        };
    };
    changePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Password changed and replacement Bearer token created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BearerToken"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["AuthenticationRequired"];
            503: components["responses"]["Error"];
        };
    };
    getCoreStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current core state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoreStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    startStrategyDiscoveryRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartRunRequest"];
            };
        };
        responses: {
            /** @description Run accepted */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    stopCurrentStrategyDiscoveryRun: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stop requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            409: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getCurrentStrategyDiscoveryProgress: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current run progress or idle state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunProgress"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCurrentStrategyDiscoveryLatestLog: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest run log tail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLogTail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getStrategyDiscoveryPreflight: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preflight facts */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreflightStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getDomainLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored domain lists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainListsResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    saveDomainList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDomainListRequest"];
            };
        };
        responses: {
            /** @description Saved list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DomainList"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    deleteUserDomainLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteDomainListRequest"];
            };
        };
        responses: {
            /** @description List deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getV2flyCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description v2fly categories */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2flyCategoriesResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getV2flyCategoryDomains: {
        parameters: {
            query: {
                /** @example youtube */
                category: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Domains from the requested category */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2flyCategoryDomainsResponse"];
                };
            };
            400: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    createBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupSnapshot"];
                };
            };
            409: components["responses"]["RuntimeBusy"];
            default: components["responses"]["Error"];
        };
    };
    listBackups: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupsResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    restoreBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackupActionRequest"];
            };
        };
        responses: {
            /** @description Restore completed synchronously. The server currently returns HTTP 202 for this completed action. */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupRestoreAccepted"];
                };
            };
            409: components["responses"]["RuntimeBusy"];
            default: components["responses"]["Error"];
        };
    };
    deleteBackup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BackupActionRequest"];
            };
        };
        responses: {
            /** @description Backup deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            409: components["responses"]["RuntimeBusy"];
            default: components["responses"]["Error"];
        };
    };
    downloadBackupArchive: {
        parameters: {
            query: {
                /** @example snapshot_20260722_173000 */
                snapshot_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup ZIP archive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/zip": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    uploadBackupFile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
                "application/zip": string;
            };
        };
        responses: {
            /** @description Backup imported */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupSnapshot"];
                };
            };
            409: components["responses"]["RuntimeBusy"];
            default: components["responses"]["Error"];
        };
    };
    createCleanInstallVault: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Pending vault created; response contains public metadata only. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanInstallVaultCreateResponse"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    listCleanInstallVaults: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public pending vault metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanInstallVaultListResponse"];
                };
            };
            400: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getCleanInstallVaultStatus: {
        parameters: {
            query: {
                /** @example 4f2a9c8e1b3d6a7f0c5e2d9b8a1f4c6e */
                vault_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Public status metadata. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanInstallVaultStatus"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    restoreCleanInstallVault: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CleanInstallVaultRestoreRequest"];
            };
        };
        responses: {
            /** @description Restore was verified and the source vault was deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CleanInstallVaultRestoreResponse"];
                };
            };
            400: components["responses"]["Error"];
            409: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getRunSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSettings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    saveRunSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunSettings"];
            };
        };
        responses: {
            /** @description Saved run settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSettings"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRunHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run history */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunHistoryResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getRunLatestLog: {
        parameters: {
            query: {
                /** @example run_20260722_173000 */
                run_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Run log tail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunLogTail"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getStrategyCandidates: {
        parameters: {
            query?: {
                /**
                 * @description Exact domain name. Returns candidates linked to this domain.
                 * @example youtube.com
                 */
                domain?: string;
                /**
                 * @description Comma-separated domain names. Returns candidates linked to any listed domain.
                 * @example youtube.com,discord.com
                 */
                domains?: string;
                /**
                 * @description Exact strategy id.
                 * @example tcp-5e8f1a2b3c4d
                 */
                strategy_id?: string;
                /**
                 * @description Strategy protocol or transport, for example tcp, quic or tls.
                 * @example tcp
                 */
                protocol?: string;
                /**
                 * @description Link source: single_domain or multi_domain.
                 * @example single_domain
                 */
                source_mode?: "single_domain" | "multi_domain";
                /**
                 * @description Normalized strategy family.
                 * @example fake-multi
                 */
                family?: string;
                /**
                 * @description Text search across id, protocol, args, family and linked domains.
                 * @example fake
                 */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Strategy candidates */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyCandidatesResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    exportStrategyCandidates: {
        parameters: {
            query?: {
                /**
                 * @description Exact domain name. Returns candidates linked to this domain.
                 * @example youtube.com
                 */
                domain?: string;
                /**
                 * @description Comma-separated domain names. Returns candidates linked to any listed domain.
                 * @example youtube.com,discord.com
                 */
                domains?: string;
                /**
                 * @description Exact strategy id.
                 * @example tcp-5e8f1a2b3c4d
                 */
                strategy_id?: string;
                /**
                 * @description Strategy protocol or transport, for example tcp, quic or tls.
                 * @example tcp
                 */
                protocol?: string;
                /**
                 * @description Link source: single_domain or multi_domain.
                 * @example single_domain
                 */
                source_mode?: "single_domain" | "multi_domain";
                /**
                 * @description Normalized strategy family.
                 * @example fake-multi
                 */
                family?: string;
                /**
                 * @description Text search across id, protocol, args, family and linked domains.
                 * @example fake
                 */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description NDJSON stream with one strategy candidate per line */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /** @example {"id":"tcp-5e8f1a2b3c4d","protocol":"tcp","args":"--dpi-desync=fake","status":"candidate"} */
                    "application/x-ndjson": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getCoreEvents: {
        parameters: {
            query?: {
                /** @example core:000000000123 */
                after_id?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Product events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getServiceStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getAvailableReleases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Available releases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AvailableReleases"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getV2flyLocalStorageStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Local v2fly storage status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["V2flyStorageStatus"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    checkV2flyUpdates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Update check completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceActionResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateV2flyLocalStorage: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Storage update completed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceActionResult"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWebStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Web UI system status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebStatusResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWebRunPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved Web UI run preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebRunPreferencesResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    saveWebRunPreferences: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebRunPreferencesSaveRequest"];
            };
        };
        responses: {
            /** @description Saved Web UI run preferences */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebRunPreferencesResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWebRunHistoryPage: {
        parameters: {
            query?: {
                /** @example 50 */
                limit?: components["parameters"]["Limit"];
                /** @example 0 */
                offset?: components["parameters"]["Offset"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated run history page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedRunHistoryResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWebCandidateDomainIndexPage: {
        parameters: {
            query?: {
                /** @example 50 */
                limit?: components["parameters"]["Limit"];
                /** @example 0 */
                offset?: components["parameters"]["Offset"];
                /** @example youtube */
                query?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated candidate domain index page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedCandidateDomainIndexResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWebStrategyCandidatesPage: {
        parameters: {
            query?: {
                /** @example 50 */
                limit?: components["parameters"]["Limit"];
                /** @example 0 */
                offset?: components["parameters"]["Offset"];
                /** @example youtube.com */
                domain?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated strategy candidates page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PagedStrategyCandidatesResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWebPresets: {
        parameters: {
            query?: {
                /** @example true */
                include_domains?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Web UI presets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebPresetsResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getWebPresetDomains: {
        parameters: {
            query: {
                /** @example finder */
                scope: components["schemas"]["WebPresetScope"];
                /** @example required */
                name: string;
                /** @example system */
                kind?: components["schemas"]["WebPresetKind"];
                /** @example youtube */
                query?: string;
                /** @example 200 */
                limit?: number;
                /** @example 0 */
                offset?: components["parameters"]["Offset"];
                /** @example true */
                include_disabled?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Preset domains page */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebPresetDomainsResponse"];
                };
            };
            400: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    saveWebPreset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebPresetSaveRequest"];
            };
        };
        responses: {
            /** @description Updated Web UI presets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebPresetsResponse"];
                };
            };
            400: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    deleteWebUserPresetLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WebPresetDeleteUserListsRequest"];
            };
        };
        responses: {
            /** @description Updated Web UI presets */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WebPresetsResponse"];
                };
            };
            400: components["responses"]["Error"];
            default: components["responses"]["Error"];
        };
    };
    getWebEvents: {
        parameters: {
            query?: {
                /** @example web:000000000123 */
                after_id?: string;
                /** @example 50 */
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description UI event slice */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventsResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    streamWebEvents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Live Web UI event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
