/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness (no token) */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log a browser in with the box's root account
         * @description Checks the password against Entware's /opt/etc/shadow (AUTH_USER / AUTH_FILES in nuxk.conf) and sets the `nuxk_agent` session cookie (HttpOnly, SameSite=Strict; forgotten after 12 h unused or a restart of nuxk-core). After 5 failures from one address the next attempts wait, doubling up to 15 min.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End the browser session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand the API token to a controller that knows the root password
         * @description nuxk-controller's setup calls this once with the root login and password the person typed; it keeps the token, never the password. Same lockout as /auth/login.
         */
        post: operations["pair"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What box this is (router or test stand), firmware, uptime */
        get: operations["info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Whole platform state — every engine plus the routing plane
         * @description Served from memory (the reconcile loop keeps it fresh); never blocks on an engine.
         */
        get: operations["status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Raw counters from /proc — rates are the reader's job */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The agent's recent log (last 500 entries kept in memory) */
        get: operations["logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live stream (Server-Sent Events)
         * @description `event: status` with a Status snapshot on connect and on every change; `event: log` with a LogEntry per new log line; a `: ping` comment every 20 s. The stream stays open until the client goes away.
         */
        get: operations["events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["engines"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engines/{kind}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One engine, read live (not from the snapshot) */
        get: operations["engine"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engines/{kind}/{action}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * start | stop | restart | probe | apply
         * @description start/stop/restart also record the run intent (the controller keeps it with backoff). probe runs an active check now (nfqws2: its probe sites, see probe-targets), keeps it as the engine's last probe and returns it. apply takes a Routing body.
         */
        post: operations["engineAction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engines/{kind}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Runtime config (xray only today); stored 0600, never served back
         * @description xray: exactly one of vless_uri (a vless:// link) or sub_url (a 3x-ui subscription; its first VLESS server). The agent renders config.json (TUN inbound opkgtunN → VLESS), xray tests it, and it replaces the old one; if xray won't start with it, the old one comes back (502). A link that can't work is 400 with the reason in words.
         */
        put: operations["engineConfig"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engines/{kind}/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** nuxk's per-domain strategies on this engine (nfqws2 only) */
        get: operations["engineStrategies"];
        /**
         * Replace nuxk's strategies (an empty list removes them)
         * @description nfqws2: each strategy becomes its own profile in NFQWS_ARGS_CUSTOM (the stock script puts it before the others) with a hostlist nuxk-sN.list of its domains and a protocol filter. Only --payload, --lua-desync, --out-range and --in-range are accepted, without files; a leading "nfqws2" and --filter-*\/--hostlist* are dropped. nfqws2 restarts; the conf is copied to nfqws2.conf.nuxk-bak first (and the original once to .nuxk-orig). If nfqws2 won't start, the old conf is restored and the answer is 502. Custom args a person wrote there themselves are never overwritten (502 with the reason).
         */
        put: operations["setEngineStrategies"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/engines/{kind}/probe-targets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The sites the probe opens (nfqws2 only)
         * @description The person's own, or — when none — up to 5 picked from nfqws2's hostlist, leaving out what the router sends into a tunnel (the person's routed Keenetic lists, nuxk's applied WARP/VLESS groups).
         */
        get: operations["engineProbeTargets"];
        /**
         * Set the probe's sites (an empty list = automatic)
         * @description Up to 10 site names; "https://site/path" is cut to the site. Each is opened over HTTPS from the router, in parallel, 8 s each.
         */
        put: operations["setEngineProbeTargets"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plane": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["plane"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plane/lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["planeLists"];
        /** Replace every list and the tunnel-down policy; the plane reconciles right away */
        put: operations["setPlaneLists"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plane/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy the user's own routed Keenetic lists into a nuxk list
         * @description The user's groups stay untouched; their domains are held back as conflicts until removed there.
         */
        post: operations["planeImport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Ok: {
            status: string;
        };
        Error: {
            error: {
                code: string;
                message: string;
            };
        };
        Credentials: {
            /** @description root (AUTH_USER) */
            user: string;
            /** Format: password */
            password: string;
        };
        SessionInfo: {
            user: string;
        };
        PairInfo: {
            /** @description the agent's API_TOKEN */
            token: string;
        };
        Version: {
            version: string;
            commit: string;
            /** @constant */
            api: "v1";
        };
        NodeInfo: {
            /**
             * @description router = Keenetic; stand = Docker prototype on the Pi
             * @enum {string}
             */
            role: "router" | "stand" | "host";
            hostname: string;
            /** @description Keenetic model (router only) */
            model?: string;
            /** @description KeeneticOS release (router only) */
            firmware?: string;
            arch: string;
            kernel: string;
            /** @description the box */
            uptime_sec: number;
            /** @description unix seconds nuxk-core started */
            core_since: number;
            version: string;
            commit: string;
        };
        Metrics: {
            /** @description unix milliseconds */
            ts: number;
            /** @description interface of the IPv4 default route */
            wan?: string;
            ifaces: {
                [key: string]: components["schemas"]["IfaceCounters"];
            };
            nfqueues: components["schemas"]["NFQueue"][];
            conntrack: number;
            conntrack_max: number;
            load1: number;
            mem_total_kb: number;
            mem_avail_kb: number;
            core_rss_kb: number;
        };
        IfaceCounters: {
            /** @description bytes received */
            rx: number;
            /** @description bytes sent */
            tx: number;
        };
        NFQueue: {
            num: number;
            /** @description packets through the queue since boot */
            packets: number;
            dropped: number;
            waiting: number;
        };
        LogEntry: {
            seq: number;
            /** @description unix milliseconds */
            ts: number;
            /** @enum {string} */
            level: "debug" | "info" | "warn" | "error";
            msg: string;
            attrs?: string;
        };
        Status: {
            version: string;
            ts: number;
            engines: components["schemas"]["EngineState"][];
            /** @description PlaneStatus, or {"backend":"off"} when the plane is off */
            plane: components["schemas"]["PlaneStatus"] | components["schemas"]["PlaneOff"];
        };
        PlaneOff: {
            /** @constant */
            backend: "off";
        };
        /** @enum {string} */
        EngineKind: "nfqws2" | "usque" | "xray";
        /** @enum {string} */
        Health: "ok" | "degraded" | "down" | "unknown";
        EngineInfo: {
            kind: components["schemas"]["EngineKind"];
            running: boolean;
            pid?: number;
            uptime_sec: number;
            version?: string;
            health: components["schemas"]["Health"];
            /** @description tunnel (opkgtun0) or, for nfqws2, the WAN it hooks */
            iface?: string;
            /** @description upstream the tunnel dials */
            endpoint?: string;
            routes: number;
            detail?: {
                [key: string]: string;
            };
        };
        /** @description EngineInfo plus the last probe and the controller's view */
        EngineState: components["schemas"]["EngineInfo"] & {
            probe?: components["schemas"]["Probe"];
            probe_at?: number;
            /** @description run intent: true keep running, false keep stopped, absent unmanaged */
            want_run?: boolean;
            last_error?: string;
        };
        Probe: {
            ok: boolean;
            egress_ip?: string;
            rtt_ms?: number;
            detail?: {
                [key: string]: string;
            };
            reason?: string;
            ts: number;
            /** @description nfqws2: one per probe site, in the order asked. ok is then "at least one site opens"; detail has opened and total. */
            checks?: components["schemas"]["ProbeCheck"][];
        };
        ProbeCheck: {
            domain: string;
            ok: boolean;
            rtt_ms?: number;
            /** @description where it broke — dns (no address), connect (no TCP), connect_timeout (TCP never answers: by IP), tls_timeout (TCP up, TLS silently dropped: by name), reset (reset during TLS: by name), cert (someone else's certificate), slow (no answer in time), error_N (curl exit N) */
            reason?: string;
        };
        ProbeSites: {
            targets: string[];
            /** @description true = picked by nuxk from the DPI list */
            auto: boolean;
        };
        Routing: {
            domains?: string[];
            cidrs?: string[];
            endpoints?: string[];
            strategy?: string;
        };
        Strategy: {
            id: string;
            /** @enum {string} */
            protocol: "tls" | "http" | "quic";
            domains: string[];
            /** @description nfqws2 desync args, e.g. "--payload=tls_client_hello --lua-desync=multisplit:pos=1" */
            args: string;
            /** @description where it was found, e.g. "gp:<run_id>" */
            source?: string;
            /**
             * Format: int64
             * @description unix seconds
             */
            applied_at?: number;
        };
        StrategySet: {
            strategies: components["schemas"]["Strategy"][];
        };
        /** @description engine-specific (xray — vless_uri or sub_url) */
        EngineConfig: {
            [key: string]: string;
        };
        /**
         * @description desync = «DPI» (nfqws2, direct); warp = usque tunnel; vless = xray tunnel
         * @enum {string}
         */
        ListMode: "desync" | "warp" | "vless";
        /**
         * @description what WARP/VLESS lists do while their tunnel is down
         * @enum {string}
         */
        OnDown: "direct" | "block";
        PlaneList: {
            name: string;
            mode: components["schemas"]["ListMode"];
            domains: string[];
            /** @description manual | imported:<group> | preset:<id> */
            source?: string;
        };
        PlaneDesired: {
            lists: components["schemas"]["PlaneList"][];
            on_down?: components["schemas"]["OnDown"];
            /** @description nuxk owns nfqws2's hostlist (set by the first DPI list) */
            manage_desync?: boolean;
        };
        PlaneGroup: {
            name: string;
            mode: components["schemas"]["ListMode"];
            interface: string;
            block: boolean;
            domains: string[];
        };
        PlaneOp: {
            /** @enum {string} */
            kind: "create-group" | "add-domains" | "del-domains" | "add-route" | "del-route" | "delete-group" | "ensure-v6-deny";
            group?: string;
            interface?: string;
            block?: boolean;
            domains?: string[];
            groups?: string[];
        };
        PlaneConflict: {
            domain: string;
            group: string;
            user_group: string;
        };
        PlaneForeign: {
            group: string;
            description?: string;
            interface: string;
            domains: string[];
        };
        PlaneStatus: {
            backend: string;
            /** @description PLANE_APPLY=1; false = plan only */
            apply: boolean;
            ifaces: {
                [key: string]: string;
            };
            on_down: components["schemas"]["OnDown"];
            groups: components["schemas"]["PlaneGroup"][] | null;
            desync: string[] | null;
            desync_ok: boolean;
            desync_managed: boolean;
            lists: components["schemas"]["PlaneList"][] | null;
            pending: components["schemas"]["PlaneOp"][] | null;
            conflicts?: components["schemas"]["PlaneConflict"][];
            foreign?: components["schemas"]["PlaneForeign"][];
            warnings?: string[];
            last_error?: string;
            checked_at?: number;
            applied_at?: number;
        };
    };
    responses: {
        /** @description error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        kind: components["schemas"]["EngineKind"];
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description alive */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        status: "ok";
                    };
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description logged in; Set-Cookie carries the session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionInfo"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            403: components["responses"]["Error"];
            404: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the session is gone, the cookie cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
        };
    };
    pair: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        responses: {
            /** @description the agent's API_TOKEN */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairInfo"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            409: components["responses"]["Error"];
            429: components["responses"]["Error"];
            503: components["responses"]["Error"];
        };
    };
    version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description build */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Version"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description node */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NodeInfo"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description counters */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Metrics"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logs: {
        parameters: {
            query?: {
                /** @description only entries with a larger seq */
                after?: number;
                /** @description at most this many, newest (default 200, max 500) */
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description entries, oldest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEntry"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    events: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/event-stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Error"];
        };
    };
    engines: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description every wired engine */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineState"][];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    engine: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["kind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description live info */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EngineInfo"];
                };
            };
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    engineAction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["kind"];
                action: "start" | "stop" | "restart" | "probe" | "apply";
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["Routing"];
            };
        };
        responses: {
            /** @description probe result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Probe"];
                };
            };
            /** @description done */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    engineConfig: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["kind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EngineConfig"];
            };
        };
        responses: {
            /** @description applied */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    engineStrategies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["kind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the stored set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategySet"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    setEngineStrategies: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["kind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StrategySet"];
            };
        };
        responses: {
            /** @description applied, nfqws2 running with them */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
            502: components["responses"]["Error"];
        };
    };
    engineProbeTargets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["kind"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description the sites and whether nuxk chose them */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeSites"];
                };
            };
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    setEngineProbeTargets: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["parameters"]["kind"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    targets: string[];
                };
            };
        };
        responses: {
            /** @description what the probe uses from now on */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProbeSites"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    plane: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description plane status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaneStatus"];
                };
            };
            /** @description plane is off (PLANE= in nuxk.conf) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    planeLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description desired lists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaneDesired"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    setPlaneLists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlaneDesired"];
            };
        };
        responses: {
            /** @description stored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ok"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
    planeImport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    groups: string[];
                    mode: components["schemas"]["ListMode"];
                };
            };
        };
        responses: {
            /** @description the new desired lists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaneDesired"];
                };
            };
            400: components["responses"]["Error"];
            404: components["responses"]["Error"];
        };
    };
}
